spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true

spring.datasource:
  hikari:
    maximum-pool-size: 4
  url: jdbc:postgresql://ec2-107-21-67-46.compute-1.amazonaws.com/df9na6p38d6j0t
  username: oczenhjtgbtdrn
  password: b8a824b049d5a1eb916d9245c4394873460b901c2a1b3a8359f8b45b6f54ee9e
  driver-class-name: org.postgresql.Driver


jwt:
  secret-key: fast_campus.sns-application_2022.secret_key
  # 30 days
  token.expired-time-ms: 2592000000